bazinga/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url


from django.contrib import admin

# from profile.forms import SignupFormExtra
from django.contrib.auth.decorators import login_required

from bazinga.views import *
from projects.views import *

# from django.conf.urls.defaults import *
# from django.views.generic.simple import direct_to_template
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

from userena import views as userena_views
from userena import settings as userena_settings
from accounts.forms import *
# import autocomplete_light.shortcuts as al


# al.autodiscover()
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
admin.autodiscover()

# al.registry.autocomplete_model_base = User
# al.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'bazinga.views.home', name='home'),
    # url(r'^bazinga/', include('bazinga.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', HomeView.as_view() , name='home'),
    # url(r'^projects/', Project().List_all_project , name='List_all_project'),
    url(r'^projects/', Project().get_repo_info , name='get_repo_info'),
    url(r'^details/', Project().get_repo_details, name='get_repo_details'),

    url(r'^accounts/', include('userena.urls')),
    # url(r'^messages/', include('userena.contrib.umessages.urls')),
    url(r'^messages/', include('django_messages.urls')),
    # url(r'^events/', include('event_rsvp.urls')),
    url(r'^todolist/', include('todolist.urls')),
    

    # url(r'^(?P<username>[\.\w]+)/edit/$',userena_views.profile_edit, {'template_name': 'userena/profile_form.html'},name='userena_profile_edit'),
    url(r'^(?P<username>[\@\.\w-]+)/password/$', userena_views.password_change, {'template_name': 'userena/profile_form.html'}, name="userena_password_change"),
    url(r'^(?P<username>[\@\.\w-]+)/email/$', userena_views.email_change, {'template_name': 'userena/profile_form.html'}, name='userena_email_change'),
    url(r'^(?P<username>[\.\w-]+)/edit/$','userena.views.profile_edit',{'edit_profile_form': CustomEditProfileForm,'template_name': 'userena/profile_form.html'},name='userena_profile_edit'),

    url(r'^todo/', todolist, name='todo'),
    url(r'^addtodo/$', addTodo, name='addtodo'),
    url(r'^todofinish/(?P<id>\d+)/$', todofinish, name='finish'),
    url(r'^todobackout/(?P<id>\d+)/$', todoback,  name='backout'),
    url(r'^updatetodo/(?P<id>\d+)/$', updatetodo, name='update'),
    url(r'^tododelete/(?P<id>\d+)/$', tododelete, name='delete'),

    # url(r'^autocomplete/', include('autocomplete_light.urls')),
    
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
   )
else:
    print "no server is configured to serve media files. Do it now."

todolist/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    '',
    url(r'^$', 'todolist.views.list_lists', name="todo-lists"),
    url(r'^mine/$', 'todolist.views.view_list', {'list_slug': 'mine'}, name="todo-mine"),
    url(r'^(?P<list_id>\d{1,4})/(?P<list_slug>[\w-]+)/delete$', 'todolist.views.del_list', name="todo-del_list"),
    url(r'^(?P<list_id>\d{1,6})/edit$', 'todolist.views.edit_list', name="todo-edit_list"),
    url(r'^task/(?P<task_id>\d{1,6})$', 'todolist.views.view_task', name='todo-task_detail'),
    url(r'^(?P<list_id>\d{1,4})/(?P<list_slug>[\w-]+)$', 'todolist.views.view_list', name='todo-incomplete_tasks'),
    url(r'^(?P<list_id>\d{1,4})/(?P<list_slug>[\w-]+)/completed$', 'todolist.views.view_list', {'view_completed': 1},
        name='todo-completed_tasks'),
    url(r'^add_list/$', 'todolist.views.add_list', name="todo-add_list"),
    url(r'^search-post/$', 'todolist.views.search_post', name="todo-search-post"),
    url(r'^search/$', 'todolist.views.search', name="todo-search"),

    # View reorder_tasks is only called by JQuery for drag/drop task ordering
    url(r'^reorder_tasks/$', 'todolist.views.reorder_tasks', name="todo-reorder_tasks"),

    url(r'^ticket/add/$', 'todolist.views.external_add', name="todo-external-add"),
    url(r'^recent/added/$', 'todolist.views.view_list', {'list_slug': 'recent-add'}, name="todo-recently_added"),
    url(r'^recent/completed/$', 'todolist.views.view_list', {'list_slug': 'recent-complete'},
        name="todo-recently_completed"),
)

bazinga/models.py
from django.db import models
import uuid
from django.utils import timezone
from django.contrib.auth.models import User, Group
from django.contrib.auth.models import *
from django.utils.translation import ugettext_lazy as _
from django_messages.models import *


class Todo(models.Model):
	user = models.ForeignKey(User, related_name='u')
	todo = models.CharField(max_length=50)
	flag = models.CharField(max_length=2, default='1')
	priority = models.CharField(max_length=2, default='0')
	pubtime = models.DateTimeField(auto_now_add=True)
	# assigned_to = models.ForeignKey(User, related_name='a')

	def __unicode__(self):
		return u'%d %s %s' % (self.id, self.todo, self.flag)

	class Meta:
		ordering = ['priority', 'pubtime']



# class MP_Draft(Message):
# 	"""docstring for MP_Draft"""
# 	is_draft = models.BooleanField(default=False)

# 	class Meta(Message.Meta):
# 		fields = Message.Meta.fields + ('is_draft')

# 	def __init__(self, arg):
# 		super(MP_Draft, self).__init__()
# 		self.arg = arg
	
# 	def save(self, **kwargs):
# 		if not self.id:
# 			self.sent_at = timezone.now()
# 		super(Message, self).save(**kwargs)

todolist/models.py
from __future__ import unicode_literals
import datetime

from django.db import models
import uuid
from django.utils import timezone
from django.contrib.auth.models import User, Group
from django.contrib.auth.models import *
from django.utils.translation import ugettext_lazy as _
from django_messages.models import *
from django.utils.encoding import python_2_unicode_compatible
from django.core.urlresolvers import reverse
from django.template.defaultfilters import slugify
from accounts.models import *





@python_2_unicode_compatible
class List(models.Model):
	name = models.CharField(max_length=60)
	slug = models.SlugField(max_length=60, editable=False)
	team = models.ForeignKey(Team)

	def save(self, *args, **kwargs):
		if not self.id:
			self.slug = slugify(self.name)

		super(List, self).save(*args, **kwargs)

	def __str__(self):
		return self.name

	# Custom manager lets us do things like Item.completed_tasks.all()
	objects = models.Manager()

	def incomplete_tasks(self):
		# Count all incomplete tasks on the current list instance
		return Item.objects.filter(list=self, completed=0)

	class Meta:
		ordering = ["name"]
		verbose_name_plural = "Lists"

		# Prevents (at the database level) creation of two lists with the same name in the same taem
		unique_together = ("team", "slug")



@python_2_unicode_compatible
class Item(models.Model):
	title = models.CharField(max_length=140)
	list = models.ForeignKey(List)
	created_date = models.DateField(auto_now=True)
	due_date = models.DateField(blank=True, null=True, )
	completed = models.BooleanField(default=None)
	completed_date = models.DateField(blank=True, null=True)
	created_by = models.ForeignKey(User, related_name='todo_created_by')
	assigned_to = models.ForeignKey(User, related_name='todo_assigned_to')
	note = models.TextField(blank=True, null=True)
	priority = models.PositiveIntegerField()

    # Model method: Has due date for an instance of this object passed?
	def overdue_status(self):
		"Returns whether the item's due date has passed or not."
		if self.due_date and datetime.date.today() > self.due_date:
			return 1

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('todo-task_detail', kwargs={'task_id': self.id, })

    # Auto-set the item creation / completed date
	def save(self):
		# If Item is being marked complete, set the completed_date
		if self.completed:
			self.completed_date = datetime.datetime.now()
		super(Item, self).save()

	class Meta:
		ordering = ["priority"]



@python_2_unicode_compatible
class Comment(models.Model):
	"""
		Not using Django's built-in comments because we want to be able to save
		a comment and change task details at the same time. Rolling our own since it's easy.
	"""
	author = models.ForeignKey(User)
	task = models.ForeignKey(Item)
	date = models.DateTimeField(default=datetime.datetime.now)
	body = models.TextField(blank=True)

	# def snippet(self):
 #        # Define here rather than in __str__ so we can use it in the admin list_display
	# 	return "{author} - {snippet}...".format(author=self.author, snippet=self.body[:35])

	def __str__(self):
		return self.body

todolist/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User, Group
from .models import Item, List
from accounts.models import *


class AddListForm(ModelForm):
    # The picklist showing allowable groups to which a new list can be added
    # determines which groups the user belongs to. This queries the form object
    # to derive that list.
    def __init__(self, user, *args, **kwargs):
        super(AddListForm, self).__init__(*args, **kwargs)
        #self.fields['team'].queryset = Team.objects.filter(user=user.profile)

    class Meta:
        model = List
        exclude = []


class EditListForm(ModelForm):
    # The picklist showing the users to which a new task can be assigned
    # must find other members of the groups the current list belongs to.
    def __init__(self, *args, **kwargs):
        super(EditListForm, self).__init__(*args, **kwargs)
        # self.fields['assigned_to'].queryset = User.objects.filter(groups__in=[self.instance.list.team])

    class Meta:
        model = List
        exclude = []


class AddItemForm(ModelForm):
    # The picklist showing the users to which a new task can be assigned
    # must find other members of the groups the current list belongs to.
    def __init__(self, task_list, *args, **kwargs):
        super(AddItemForm, self).__init__(*args, **kwargs)
        # print dir(self.fields['list'])
        # print self.fields['list'].initial
        # self.fields['assigned_to'].queryset = User.profile.objects.filter(teams__in=[task_list.team])
        self.fields['assigned_to'].label_from_instance = \
            lambda obj: "%s (%s)" % (obj.get_full_name(), obj.username)

    due_date = forms.DateField(
        required=False,
        widget=forms.DateTimeInput(attrs={'class': 'due_date_picker'})
    )

    title = forms.CharField(
        widget=forms.widgets.TextInput(attrs={'size': 35})
    )

    note = forms.CharField(widget=forms.Textarea(), required=False)

    class Meta:
        model = Item
        exclude = []


class EditItemForm(ModelForm):
    # The picklist showing the users to which a new task can be assigned
    # must find other members of the groups the current list belongs to.
    def __init__(self, *args, **kwargs):
        super(EditItemForm, self).__init__(*args, **kwargs)
        # self.fields['assigned_to'].queryset = User.objects.filter(groups__in=[self.instance.list.team])

    class Meta:
        model = Item
        exclude = ('created_date', 'created_by',)


class AddExternalItemForm(ModelForm):
    """Form to allow users who are not part of the GTD system to file a ticket."""

    title = forms.CharField(
        widget=forms.widgets.TextInput(attrs={'size': 35})
    )
    note = forms.CharField(
        widget=forms.widgets.Textarea(),
        help_text='Foo',
    )

    class Meta:
        model = Item
        exclude = ('list', 'created_date', 'due_date', 'created_by', 'assigned_to',)


class SearchForm(forms.Form):
    """Search."""

    q = forms.CharField(
        widget=forms.widgets.TextInput(attrs={'size': 35})
    )

bazinga/views.py
from django.views.generic import TemplateView
from django import forms
from projects.models import *
from django.views.decorators.csrf import csrf_exempt

from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from django.template import RequestContext
from django.contrib.auth.models import User
from django.http import Http404
from .models import Todo
from django.template import *
from django.template import RequestContext


# def home(request):
# 	return render_to_response('userena/profile_form.html', {}, context_instance=RequestContext(request))



class HomeView(TemplateView):
    template_name = "index.html"

class ProjectsView(TemplateView):
    template_name = "projects.html"



def todolist(request):
	user = User.objects.get(username=request.user.username)
	todolist = Todo.objects.filter(flag=1,user_id=user)
	finishtodos = Todo.objects.filter(flag=0,user_id=user)
	return render_to_response('simpleTodo.html',
		{'todolist': todolist, 'finishtodos': finishtodos},
		context_instance=RequestContext(request))

def todofinish(request, id=''):
	todo = Todo.objects.get(id=id)
	if todo.flag == '1':
		todo.flag = '0'
		todo.save()
		return HttpResponseRedirect('/todo/')
	user = User.objects.get(username=request.user.username)
	todolist = Todo.objects.filter(flag=1, user_id=user)
	return render_to_response('simpleTodo.html', {'todolist': todolist},
		context_instance=RequestContext(request))


def todoback(request, id=''):
	todo = Todo.objects.get(id=id)
	user = User.objects.get(username=request.user.username)
	if todo.flag == '0':
		todo.flag = '1'
		todo.save()
		return HttpResponseRedirect('/todo/')
		todolist = Todo.objects.filter(flag=1, user_id=user)
	return render_to_response('simpleTodo.html', {'todolist': todolist},
		context_instance=RequestContext(request))


def tododelete(request, id=''):
	try:
		todo = Todo.objects.get(id=id)
	except Exception:
		raise Http404
	if todo:
		todo.delete()
		return HttpResponseRedirect('/todo/')
	user = User.objects.get(username=request.user.username)
	todolist = Todo.objects.filter(flag=1, user_id=user)
	return render_to_response('simpleTodo.html', {'todolist': todolist},
		context_instance=RequestContext(request))


def addTodo(request):
	if request.method == 'POST':
		atodo = request.POST['todo']
		priority = request.POST['priority']
		user = User.objects.get(username=request.user.username)
		todo = Todo(user=user, todo=atodo, priority=priority, flag='1')
		todo.save()
		user = User.objects.get(username=request.user.username)
		todolist = Todo.objects.filter(flag=1, user_id=user)
		finishtodos = Todo.objects.filter(flag=0, user_id=user)
		return render_to_response('simpleTodo.html',
			{'todolist': todolist, 'finishtodos': finishtodos},
			context_instance=RequestContext(request))
	else:
		user = User.objects.get(username=request.user.username)
		todolist = Todo.objects.filter(flag=1, user_id=user)
		finishtodos = Todo.objects.filter(flag=0, user_id=user)
		return render_to_response('simpleTodo.html',
			{'todolist': todolist, 'finishtodos': finishtodos})


def updatetodo(request, id=''):
	if request.method == 'POST':
		print 'ddd'
		atodo = request.POST['todo']
		priority = request.POST['priority']
		user = User.objects.get(username=request.user.username)
		todo = Todo(user=user, todo=atodo, priority=priority, flag='1')
		todo.save()
		todolist = Todo.objects.filter(flag=1, user_id=user)
		finishtodos = Todo.objects.filter(flag=0, user_id=user)
		return render_to_response('simpleTodo.html',
			{'todolist': todolist, 'finishtodos': finishtodos},
			context_instance=RequestContext(request))
	else:
		try:
			todo = Todo.objects.get(id=id)
		except Exception:
			raise Http404
		return render_to_response('updatatodo.html', {'todo': todo},
			context_instance=RequestContext(request))


# def site_info(request, template_name='django_messages/inbox.html'):

# 	site_info = RequestContext(request)
# 	# return render_to_response(template_name, site_info)
# 	print "======================================================="
# 	print "ok"
# 	print "======================================================="
# 	return render_to_response(template_name, context, context_instance=RequestContext(request))

def details(request, template_name="index.html"):
	return render_to_response(template_name, context, context_instance=RequestContext(request))

bazinga/templates/todolist/add_list.html
{% extends "todolist/base.html" %}
{% block page_heading %}{% endblock %}
{% block title %}Add Todo List{% endblock %}

{% block content %}


<form action="{% url 'todo-add_list' %}" method="post">
		{% csrf_token %}
<div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Add a list:</h4>
      </div>
	
	
		<div class="modal-body">
			<table>{{ form }}</table>
		</div>
	
	<div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
      </div>
</form>	

{% endblock %}

bazinga/templates/todolist/base.html
{% extends "base.html" %}
{% load url from future %}
{% load staticfiles %}


	<!-- CSS and JavaScript for django-todo -->
	<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}todo/css/styles.css" />

	<script src="{{STATIC_URL}}todo/js/jquery.tablednd_0_5.js" type="text/javascript"></script>


	<script type="text/javascript" src="http://code.jquery.com/jquery-1.3.2.min.js"></script>
	<script type="text/javascript" src="{{MEDIA_URL}}js/ui.core.js"></script>
	<link type="text/css" href="{{MEDIA_URL}}js/jquery-ui-1.7.1.custom.css" rel="Stylesheet" />
	<script src="{{MEDIA_URL}}js/ui.datepicker.js" type="text/javascript"></script>

	<script type="text/javascript" charset="utf-8">
	    // thedate.x comes from the edit_task view. If this is a new entry,
	    // thedate won't be present and datepicker will fall back on the default (today).
	    $(document).ready(function(){
	        $('#id_due_date').datepicker({defaultDate: new Date({{thedate.year}}, {{thedate.month}} - 1, {{thedate.day}}),});
	     });
	</script>

bazinga/templates/todolist/del_list.html
{% extends "todolist/base.html" %}
{% load url from future %}

{% block title %}{{ list_title }} to-do items{% endblock %}

{% block content %}

    {# Only admins can delete lists. #}
    {% ifequal can_del 1 %}


        {% if list_killed %}

           <p> {{ list.name }} is gone.</p>

            <a href="{% url 'todo-lists' %}">Return to lists</a>

        {% else %}

            <h1>Delete entire list: {{ list.name }} ?</h1>

            <p>Category tally:</p>

             <ul>
                <li>Incomplete: {{ item_count_undone }} </li>
                <li>Complete: {{ item_count_done }} </li>
                <li><strong>Total: {{ item_count_total }}</strong> </li>
             </ul>

            <p> ... all of which will be irretrievably <strong>blown away</strong>. Are you sure you want to do that?</p>

            <form action="" method="post" accept-charset="utf-8">
    		{% csrf_token %}

                <input type="hidden" name="list" value="{{ list.id }}" id="some_name">
             <p><input type="submit" name="delete-confirm" value="Do it! &rarr;" class="todo-button"> </p>
            </form>


            <a href="{% url 'todo-incomplete_tasks' list.id list_slug %}">Return to list: {{ list.name }}</a>

        {% endif %}


    {% else %}

        <p>Sorry, you don't have permission to delete lists. Please contact your group administrator.</p>

    {% endifequal %}


{% endblock %}

bazinga/templates/todolist/edit_list.html
{% extends "todolist/base.html" %}
{% load url from future %}

{% block title %}{{ list_title }} to-do items{% endblock %}

{% block content %}

    {# Only admins can delete lists. #}
    {% ifequal can_edit 1 %}


        
           <form action="{% url 'todo-edit_list' list.id %}" method="post">
        {% csrf_token %}
<div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Add a list:</h4>
      </div>
    
    
        <div class="modal-body">
            <table>{{ form }}</table>
        </div>
    
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
      </div>
</form> 


    {% else %}

        <p>Sorry, you don't have permission to delete lists. Please contact your group administrator.</p>

    {% endifequal %}


{% endblock %}

bazinga/templates/todolist/view_list.html
{% extends "todolist/base.html" %}
{% load url from future %}
{% load i18n %}
{% load staticfiles %}
{% block title %}Todo List: {{ list.name }}{% endblock %}

{% block content %}
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  <link rel="stylesheet" href="/resources/demos/style.css">
    <script type="text/javascript">
    function order_tasks(data) {
        // The JQuery plugin tableDnD provides a serialize() function which provides the re-ordered
        // data in a list. We pass that list as an object called "data" to a Django view
        // to save the re-ordered data into the database.
        $.post("{% url 'todo-reorder_tasks' %}", data, "json");
        return false;
    };
    $(document).ready(function() {
        // Initialise the task table for drag/drop re-ordering
        $("#tasktable").tableDnD();
        $('#tasktable').tableDnD({
            onDrop: function(table, row) {
                order_tasks($.tableDnD.serialize());
            }
        });
        // Initially hide the Add Task form
        $('#AddTask').hide();
        // toggle slide to show the Add Task form when link clicked
        $('#slideToggle').click(function(){
            $(this).siblings('#AddTask').slideToggle();
        });
    });
    </script>


    {% ifequal list_slug "mine" %}
        <h1>Tasks assigned to {{ request.user }}</h1>
    {% else %}
        {% ifequal auth_ok 1 %}
           <h1>Tasks filed under "{{ list.name }}"</h1>
           <p>This list belongs to group {{ list.team }}</p>
        {% endifequal %}
    {% endifequal %}


    {% ifequal auth_ok 1 %}
        <form action="" method="POST">
        {% csrf_token %}

   {# Only show task adder if viewing a proper list #}
   {% ifnotequal list_slug "mine" %}
   <h2 style="margin-bottom:0px;" id="slideToggle" >&rarr; Click to add task &larr;</h2>

   <div id="AddTask">
	    <table class="nocolor" border="0" cellspacing="5" cellpadding="5">
	       <tr>
	           <td>{{ form.title.errors }}</td>
	           <td>{{ form.due_date.errors }}</td>
	       </tr>
	       <tr>
	           <td><label for="id_title">Task:</label> {{ form.title }}</td>
	           <td><label for="id_due_date">Due date:</label> {{ form.due_date }}</td>
	           <td><label for="id_assigned">Assign to:</label> {{ form.assigned_to }}</td>
	           <td><label for="id_notify">Notify*:</label> <input type="checkbox" checked="checked" name="notify" value="1" id="notify"></td>
 	       </tr>
	       <tr>
	           <td><label for="id_note">Note:</label>
                    {{ form.note }}
	               <p class="minor">*Email notifications will only be sent if task is assigned to someone besides yourself.</p>
	           </td>
 	       </tr>
	    

        <tr>
            <label for="id_priority">priority:</label>
            <!-- <input type="text" name="priority" id="id_priority"> -->
            <select name="priority" id="id_priority">
                <option selected="selected" value="">---------</option>
                <option value="1">High</option>
                <option value="2">Medium</option>
                <option value="3">Low</option>
            </select>
        </tr>
        </table>
        <input type="text" name="created_by" value="{{ request.user.id }}" id="id_created_by">
        <input type="text" name="list" value="{{ listid }}" id="id_list">
        <input type="text" name="created_date" value="{{ created_date }}" id="id_created_date">

	    <p><input type="submit" name="add_task" value="Add task" class="todo-button"></p>
    </div>

        {% endifnotequal %}


    {% ifequal view_completed 0  %}

	<h3>Incomplete tasks :: Drag rows to set priorities</h3>

	<table border="0" id="tasktable">
        <tr>
            <th>Done</th>
            <th>Task</th>
            <th>Created</th>
            <th>Due on</th>
            <th>Owner</th>
            <th>Assigned</th>
            <th>Note</th>
            <th>Comm</th>

            {% ifequal list_slug "mine" %}
            <th>List</th>
             {% endifequal %}

            <th>Del</th>
        </tr>
		{% for task in task_list %}
	        <tr id="{{ task.id }}">
	            <td><input type="checkbox" name="mark_done" value="{{ task.id }}" id="mark_done_{{ task.id }}">   </td>
	            <td><a href="{% url 'todo-task_detail' task.id %}">{{ task.title|truncatewords:20 }}</a></td>
	            <td>{{ task.created_date|date:"m/d/Y" }}</td>
	            <td>
	            {% if task.overdue_status %}<span class="overdue">{% endif %}
	                {{ task.due_date|date:"m/d/Y" }}
	            {% if task.overdue_status %}</span>{% endif %}
	            </td>
	            <td>{{ task.created_by }}</td>
	            <td>{{ task.assigned_to }}</td>
	            <td style="text-align:center;">{% if task.note %}&asymp;{% endif %} </td>
	            <td style="text-align:center;">{% ifnotequal task.comment_set.all.count 0  %}{{ task.comment_set.all.count }}{% endifnotequal %}

	            </td>
	            {% ifequal list_slug "mine" %}
                <td><a href="{% url 'todo-incomplete_tasks' task.list.id task.list.slug %}">{{ task.list }}</a></td>
                {% endifequal %}

	            <td><input type="checkbox" name="del_task" value="{{ task.id }}" id="del_task_{{ task.id }}">   </td>
            </tr>
	    {% endfor %}
	</table>
    <p><input type="submit" name="mark_tasks_done" value="Continue..."  class="todo-button"></p>

    <p><a  class="todo" href="{% url 'todo-completed_tasks' list_id list_slug %}">View completed tasks</a></p>
    {% endifequal %}

    {% ifequal view_completed 1 %}
	<h3>Completed tasks</h3>

	<table border="0"  id="tasktable">
        <tr>
            <th>Undo</th>
            <th>Task</th>
            <th>Created</th>
            <th>Completed on</th>
            <th>Note</th>
            <th>Comm</th>
            {% ifequal list_slug "mine" %}
            <th>List</th>
             {% endifequal %}
            <th>Del</th>
        </tr>


		{% for task in completed_list %}
	        <tr>
	            <td><input type="checkbox" name="undo_completed_task" value="{{ task.id }}" id="id_undo_completed_task{{ task.id }}">   </td>
	            <td><a href="{% url 'todo-task_detail' task.id %}">{{ task.title|truncatewords:20 }}</a></td>
	            <td>{{ task.created_date|date:"m/d/Y" }}</td>
	            <td>{{ task.completed_date|date:"m/d/Y" }}</td>
	            <td style="text-align:center;">{% if task.note %}&asymp;{% endif %} </td>
	            <td style="text-align:center;">{% ifnotequal task.comment_set.all.count 0  %}{{ task.comment_set.all.count }}{% endifnotequal %}

	            <td><input type="checkbox" name="del_completed_task" value="{{ task.id }}" id="del_completed_task_{{ task.id }}">   </td>
            </tr>
	    {% endfor %}

	</table>
	<p><input type="submit" name="deldonetasks" value="Continue..."  class="todo-button"></p>
	</form>
    <p><a  class="todo" href="{% url 'todo-incomplete_tasks' list_id list_slug %}">View incomplete tasks</a></p>
    {% endifequal %}

	{% ifequal can_del 1 %}
	{% ifnotequal list_slug "mine" %}
	   <p><a class="todo" href="{% url 'todo-del_list' list_id list_slug %}">Delete this list</a></p>
	{% endifnotequal %}
	{% endifequal %}

    {% endifequal %}
{% endblock %}