bazinga/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url


from django.contrib import admin

# from profile.forms import SignupFormExtra
from django.contrib.auth.decorators import login_required

from bazinga.views import *
from projects.views import *

# from django.conf.urls.defaults import *
# from django.views.generic.simple import direct_to_template
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

from userena import views as userena_views
from userena import settings as userena_settings
from accounts.forms import *
# import autocomplete_light.shortcuts as al


# al.autodiscover()
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
admin.autodiscover()

# al.registry.autocomplete_model_base = User
# al.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'bazinga.views.home', name='home'),
    # url(r'^bazinga/', include('bazinga.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', HomeView.as_view() , name='home'),
    # url(r'^projects/', Project().List_all_project , name='List_all_project'),
    url(r'^projects/', Project().get_repo_info , name='get_repo_info'),
    url(r'^details/', Project().get_repo_details, name='get_repo_details'),

    url(r'^accounts/', include('userena.urls')),
    # url(r'^messages/', include('userena.contrib.umessages.urls')),
    url(r'^messages/', include('django_messages.urls')),
    # url(r'^events/', include('event_rsvp.urls')),
    url(r'^todolist/', include('todolist.urls')),
    

    # url(r'^(?P<username>[\.\w]+)/edit/$',userena_views.profile_edit, {'template_name': 'userena/profile_form.html'},name='userena_profile_edit'),
    url(r'^(?P<username>[\@\.\w-]+)/password/$', userena_views.password_change, {'template_name': 'userena/profile_form.html'}, name="userena_password_change"),
    url(r'^(?P<username>[\@\.\w-]+)/email/$', userena_views.email_change, {'template_name': 'userena/profile_form.html'}, name='userena_email_change'),
    url(r'^(?P<username>[\.\w-]+)/edit/$','userena.views.profile_edit',{'edit_profile_form': CustomEditProfileForm,'template_name': 'userena/profile_form.html'},name='userena_profile_edit'),

    url(r'^todo/', todolist, name='todo'),
    url(r'^addtodo/$', addTodo, name='addtodo'),
    url(r'^todofinish/(?P<id>\d+)/$', todofinish, name='finish'),
    url(r'^todobackout/(?P<id>\d+)/$', todoback,  name='backout'),
    url(r'^updatetodo/(?P<id>\d+)/$', updatetodo, name='update'),
    url(r'^tododelete/(?P<id>\d+)/$', tododelete, name='delete'),

    # url(r'^autocomplete/', include('autocomplete_light.urls')),
    
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
   )
else:
    print "no server is configured to serve media files. Do it now."

todolist/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    '',
    url(r'^$', 'todolist.views.list_lists', name="todo-lists"),
    url(r'^mine/$', 'todolist.views.view_list', {'list_slug': 'mine'}, name="todo-mine"),
    url(r'^(?P<list_id>\d{1,4})/(?P<list_slug>[\w-]+)/delete$', 'todolist.views.del_list', name="todo-del_list"),
    url(r'^(?P<list_id>\d{1,6})/edit$', 'todolist.views.edit_list', name="todo-edit_list"),
    url(r'^task/(?P<task_id>\d{1,6})$', 'todolist.views.view_task', name='todo-task_detail'),
    url(r'^(?P<list_id>\d{1,4})/(?P<list_slug>[\w-]+)$', 'todolist.views.view_list', name='todo-incomplete_tasks'),
    url(r'^(?P<list_id>\d{1,4})/(?P<list_slug>[\w-]+)/completed$', 'todolist.views.view_list', {'view_completed': 1},
        name='todo-completed_tasks'),
    url(r'^add_list/$', 'todolist.views.add_list', name="todo-add_list"),
    url(r'^search-post/$', 'todolist.views.search_post', name="todo-search-post"),
    url(r'^search/$', 'todolist.views.search', name="todo-search"),

    # View reorder_tasks is only called by JQuery for drag/drop task ordering
    url(r'^reorder_tasks/$', 'todolist.views.reorder_tasks', name="todo-reorder_tasks"),

    url(r'^ticket/add/$', 'todolist.views.external_add', name="todo-external-add"),
    url(r'^recent/added/$', 'todolist.views.view_list', {'list_slug': 'recent-add'}, name="todo-recently_added"),
    url(r'^recent/completed/$', 'todolist.views.view_list', {'list_slug': 'recent-complete'},
        name="todo-recently_completed"),
)

accounts/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _
from userena.models import UserenaBaseProfile
from django.core.validators import URLValidator
from django.contrib import admin


#from phonenumber_field.modelfields import PhoneNumberField

class Team(models.Model):
	"""docstring for Team"""
	uuid = models.AutoField(primary_key=True)
	name = models.CharField(max_length=100, unique=True, blank=False, null=False)
	description = models.TextField(blank=True, null=True)
	mentor = models.OneToOneField(User,unique=True,verbose_name=_('mentor'),related_name='mentor')
	def __unicode__(self):
		return self.name

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = _('team')
		verbose_name_plural = _('teams')

	# Custom manager lets us do things like Item.completed_tasks.all()
	objects = models.Manager()

class MyProfile(UserenaBaseProfile):
	user = models.OneToOneField(User,unique=True,verbose_name=_('user'),related_name='profile')
	team = models.OneToOneField(Team,unique=True,verbose_name=_('team'),related_name='team')
	# team = models.ForeignKey(Team,blank=True, null=True)
	birth_date = models.DateField(blank=True, null=True)
	address = models.TextField(blank=True, null=True)
	#telephone = models.PhoneNumberField(blank=True)
	about = models.TextField(blank=True, null=True)
	city = models.CharField(max_length=100,blank=True, null=True)
	GENDER_CHOICES = (('M', 'Male'),('F', 'Female'))
	gender = models.CharField(max_length=1, choices=GENDER_CHOICES,blank=True, null=True)
	github = models.CharField(max_length=100,validators=[URLValidator()],blank=True, null=True)
	facebook = models.CharField(max_length=100,validators=[URLValidator()],blank=True, null=True)
	twitter = models.CharField(max_length=100,validators=[URLValidator()],blank=True, null=True)
	googleplus = models.CharField(max_length=100,validators=[URLValidator()],blank=True, null=True)
	website = models.CharField(max_length=100,validators=[URLValidator()],blank=True, null=True)

	objects = models.Manager()

class TeamAdmin(admin.ModelAdmin):
    search_fields = ["name"]
    list_display = ["name"]

bazinga/models.py
from django.db import models
import uuid
from django.utils import timezone
from django.contrib.auth.models import User, Group
from django.contrib.auth.models import *
from django.utils.translation import ugettext_lazy as _
from django_messages.models import *


class Todo(models.Model):
	user = models.ForeignKey(User, related_name='u')
	todo = models.CharField(max_length=50)
	flag = models.CharField(max_length=2, default='1')
	priority = models.CharField(max_length=2, default='0')
	pubtime = models.DateTimeField(auto_now_add=True)
	# assigned_to = models.ForeignKey(User, related_name='a')

	def __unicode__(self):
		return u'%d %s %s' % (self.id, self.todo, self.flag)

	class Meta:
		ordering = ['priority', 'pubtime']



# class MP_Draft(Message):
# 	"""docstring for MP_Draft"""
# 	is_draft = models.BooleanField(default=False)

# 	class Meta(Message.Meta):
# 		fields = Message.Meta.fields + ('is_draft')

# 	def __init__(self, arg):
# 		super(MP_Draft, self).__init__()
# 		self.arg = arg
	
# 	def save(self, **kwargs):
# 		if not self.id:
# 			self.sent_at = timezone.now()
# 		super(Message, self).save(**kwargs)

bazinga/views.py
from django.views.generic import TemplateView
from django import forms
from projects.models import *
from django.views.decorators.csrf import csrf_exempt

from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from django.template import RequestContext
from django.contrib.auth.models import User
from django.http import Http404
from .models import Todo
from django.template import *
from django.template import RequestContext


# def home(request):
# 	return render_to_response('userena/profile_form.html', {}, context_instance=RequestContext(request))



class HomeView(TemplateView):
    template_name = "index.html"

class ProjectsView(TemplateView):
    template_name = "projects.html"



def todolist(request):
	user = User.objects.get(username=request.user.username)
	todolist = Todo.objects.filter(flag=1,user_id=user)
	finishtodos = Todo.objects.filter(flag=0,user_id=user)
	return render_to_response('simpleTodo.html',
		{'todolist': todolist, 'finishtodos': finishtodos},
		context_instance=RequestContext(request))

def todofinish(request, id=''):
	todo = Todo.objects.get(id=id)
	if todo.flag == '1':
		todo.flag = '0'
		todo.save()
		return HttpResponseRedirect('/todo/')
	user = User.objects.get(username=request.user.username)
	todolist = Todo.objects.filter(flag=1, user_id=user)
	return render_to_response('simpleTodo.html', {'todolist': todolist},
		context_instance=RequestContext(request))


def todoback(request, id=''):
	todo = Todo.objects.get(id=id)
	user = User.objects.get(username=request.user.username)
	if todo.flag == '0':
		todo.flag = '1'
		todo.save()
		return HttpResponseRedirect('/todo/')
		todolist = Todo.objects.filter(flag=1, user_id=user)
	return render_to_response('simpleTodo.html', {'todolist': todolist},
		context_instance=RequestContext(request))


def tododelete(request, id=''):
	try:
		todo = Todo.objects.get(id=id)
	except Exception:
		raise Http404
	if todo:
		todo.delete()
		return HttpResponseRedirect('/todo/')
	user = User.objects.get(username=request.user.username)
	todolist = Todo.objects.filter(flag=1, user_id=user)
	return render_to_response('simpleTodo.html', {'todolist': todolist},
		context_instance=RequestContext(request))


def addTodo(request):
	if request.method == 'POST':
		atodo = request.POST['todo']
		priority = request.POST['priority']
		user = User.objects.get(username=request.user.username)
		todo = Todo(user=user, todo=atodo, priority=priority, flag='1')
		todo.save()
		user = User.objects.get(username=request.user.username)
		todolist = Todo.objects.filter(flag=1, user_id=user)
		finishtodos = Todo.objects.filter(flag=0, user_id=user)
		return render_to_response('simpleTodo.html',
			{'todolist': todolist, 'finishtodos': finishtodos},
			context_instance=RequestContext(request))
	else:
		user = User.objects.get(username=request.user.username)
		todolist = Todo.objects.filter(flag=1, user_id=user)
		finishtodos = Todo.objects.filter(flag=0, user_id=user)
		return render_to_response('simpleTodo.html',
			{'todolist': todolist, 'finishtodos': finishtodos})


def updatetodo(request, id=''):
	if request.method == 'POST':
		print 'ddd'
		atodo = request.POST['todo']
		priority = request.POST['priority']
		user = User.objects.get(username=request.user.username)
		todo = Todo(user=user, todo=atodo, priority=priority, flag='1')
		todo.save()
		todolist = Todo.objects.filter(flag=1, user_id=user)
		finishtodos = Todo.objects.filter(flag=0, user_id=user)
		return render_to_response('simpleTodo.html',
			{'todolist': todolist, 'finishtodos': finishtodos},
			context_instance=RequestContext(request))
	else:
		try:
			todo = Todo.objects.get(id=id)
		except Exception:
			raise Http404
		return render_to_response('updatatodo.html', {'todo': todo},
			context_instance=RequestContext(request))


# def site_info(request, template_name='django_messages/inbox.html'):

# 	site_info = RequestContext(request)
# 	# return render_to_response(template_name, site_info)
# 	print "======================================================="
# 	print "ok"
# 	print "======================================================="
# 	return render_to_response(template_name, context, context_instance=RequestContext(request))

def details(request, template_name="index.html"):
	return render_to_response(template_name, context, context_instance=RequestContext(request))

bazinga/templates/userena/activate_retry.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}


{% block title %}{% trans "Account activation failed." %}{% endblock %}
{% block content_title %}<h2>{% trans "Your account could not be activated..." %}</h2>{% endblock %}

{% block content %}
<p>{% trans "Your account could not be activated because activation link is expired." %}</p>
<p><a href="{% url 'userena_activate_retry' activation_key %}">{% trans "Request a new activation link." %}</a></p>
{% endblock %}

bazinga/templates/userena/disabled.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}

{% block title %}{% trans "Disabled account" %}{% endblock %}
{% block content_title %}<h2>{% trans "Your account has been disabled" %}</h2>{% endblock %}
{% block content %}
<p>{% trans "It seems your account has been disabled." %}</p>
<p>{% trans "If you feel that injustice has been done to you, feel free to contact the administrators to find out why" %}</p>
{% endblock %} 

bazinga/templates/userena/email_change_complete.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}

{% block title %}{% trans "Email verification" %}{% endblock %}
{% block content_title %}<h2>{% trans 'Confirm your new email' %}</h2>{% endblock %}

{% block content %}
<p>{% blocktrans with viewed_user.userena_signup.email_unconfirmed as email %}You have received an email at {{ email }}.{% endblocktrans %}</p>
<p>{% blocktrans with viewed_user.username as username %}To associate this email address with your account ({{ username }}) click on the link provided in this email.{% endblocktrans %}</p>
{% endblock %}

bazinga/templates/userena/email_confirm_complete.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}

{% block title %}{% trans "Email changed!" %}{% endblock %}

{% block content_title %}<h2>{% trans 'New email' %}</h2>{% endblock %}
{% block content %}
<p>{% blocktrans with site.name as site %}Your new email address is saved. You can continue using {{ site }} with this email.{% endblocktrans %}</p>
{% endblock %}

bazinga/templates/userena/password_complete.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}

{% block title %}{% trans "Password changed" %}{% endblock %}
{% block content_title %}<h2>{% trans "Your password has been changed" %}.</h2>{% endblock %}

{% block content %}
<p>{% trans "From now on you can use your new password to signin" %}.</p>
{% endblock %}

bazinga/templates/userena/password_form.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}

{% block title %}{% trans "Change password" %}{% endblock %}

{% block content_title %}<h2 class="content-title">Account &raquo; {{ account.user.username }}</h2>{% endblock %}

{% block content %}

<ul id="profile-nav">
     <li><a href="{% url 'userena_profile_detail' user.username %}">{% trans "View profile" %}</a></li>
     <li><a href="{% url 'userena_profile_edit' user.username %}">{% trans "Edit details" %}</a></li>
     <li class="selected"><a href="{% url 'userena_password_change' user.username %}">{% trans "Change password" %}</a></li>
     <li><a href="{% url 'userena_email_change' user.username %}">{% trans "Change email" %}</a></li>
 </ul>

<form action="" method="post" id="password_change_form">
    {% if user.username == account.user.username %}
          <ul id="box-nav">
              <li class="first"><a href="{% url 'userena_detail' user.username %}"><span>{% trans 'View profile' %}</span></a></li>
              <li><a href="{% url 'userena_edit' account.user.username %}">{% trans "Edit profile" %}</a></li>
              <li  class="selected"><a href="{% url 'userena_password_change' account.user.username %}">{% trans "Change password" %}</a></li>
              <li class="last"><a href="{% url 'userena_email_change' account.user.username %}">{% trans "Change email" %}</a></li>
          </ul>
          {% endif %}
    <fieldset>
        <legend>{% trans "Change Password" %}</legend>
        {% csrf_token %}
        {{ form.as_p }}
    </fieldset>
    <input type="submit" value="{% trans "Change password" %}" />
</form>
{% endblock %}

bazinga/templates/userena/password_reset_complete.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}

{% block title %}{% trans "Password reset" %}{% endblock %}
{% block content_title %}<h2>{% trans "Your password has been reset" %}</h2>{% endblock %}
{% block content %}
{% url 'userena_signin' as signin_url %}
{% blocktrans %}You can now <a href="{{ signin_url }}">signin</a> with your new password.{% endblocktrans %}
{% endblock %}

bazinga/templates/userena/password_reset_confirm_form.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}

{% block title %}{% trans "Reset password" %}{% endblock %}

{% block content %}
<form action="" method="post">
  <fieldset>
    <legend>{% trans "Reset Password" %}</legend>
    {% csrf_token %}
    {{ form.as_p }}
  </fieldset>
  <input type="submit" value="{% trans "Reset password" %}" />
</form>
{% endblock %}

bazinga/templates/userena/password_reset_done.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}

{% block title %}{% trans "Password reset email sent" %}{% endblock %}
{% block content_title %}<h2>{% trans "Password reset email sent" %}</h2>{% endblock %}

{% block content %}
<p>{% trans "An e-mail has been sent to you which explains how to reset your password." %}</p>
{% endblock %}

bazinga/templates/userena/password_reset_form.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load staticfiles %}
{% load widget_tweaks %}
{% block title %}{% trans "Reset password" %}{% endblock %}

{% block content %}
<link href="{% static "css/profile.css" %}" rel="stylesheet">
{% include "navbar.html" %}


<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <div class="main-header page-header">
                <h2>{% trans "Reset Password" %}</h2>
            </div>
        </div>         
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel-body">
                <div class="main-content">
                    <div class="row">
                        <form action="" method="post">
						 
						    <div class="col-lg-2">
							    {% csrf_token %}
							    {{ form.as_p }}
						   	</div>
						   	<div class="col-lg-1">
						  		<input class="btn btn-custom-primary" type="submit" value="{% trans "Reset password" %}" />
						  	</div>
						</form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock %}

bazinga/templates/userena/profile_form.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}
{% load staticfiles %}
{% load widget_tweaks %}
{% block title %}{% trans "Account setup" %}{% endblock %}

{% block content_title %}<h2 class="content-title">Account &raquo; {{ account.user.username }}</h2>{% endblock %}

{% block content %}

<!-- <link href="{% static "css/jquery-ui.css" %}" rel="stylesheet"> -->
<link rel="stylesheet" href="http://code.jquery.com/ui/1.11.2/themes/flick/jquery-ui.css">
<!-- <script src="http://code.jquery.com/jquery-1.10.2.js"></script>  -->
<script src="http://code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
<link href="{% static "css/profile.css" %}" rel="stylesheet">

<!-- ######################################################################################## -->

<script>  $(function() {
    
    $( "#id_birth_date" ).datepicker(
        {
            changeMonth: true,
            changeYear: true,
            dateFormat: "yy-mm-dd",
            // minDate: "-80Y",
            // maxDate: "-10Y",
            minDate: new Date(1900, 10 - 1, 25),
        });  
});  
</script>

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <div class="main-header page-header">
                <h2>{% trans "Edit Profile" %}</h2>
                <em><b>{{ profile.user.username }}</b></em>
            </div>
        </div>
                <!-- /.col-lg-12 -->
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel-body">
                <div class="main-content">
                    <!-- NAV TABS -->
                    <ul id="profile-nav" class="nav nav-tabs">
                        <li>
                            <a href="{% url 'userena_profile_detail' user.username %}"><i class="fa fa-user"></i> {% trans "View profile" %}</a>
                        </li>
                        <li class="{% ifequal request.path|slice:"-6:" "/edit/" %}active{% endifequal %}">
                            <a href="{% url 'userena_profile_edit' user.username %}"><i class="fa fa-cogs"></i> {% trans "Edit details" %}</a>
                        </li>
                        <li class="{% ifequal request.path|slice:"-10:" "/password/" %}active{% endifequal %}">
                            <a href="{% url 'userena_password_change' user.username %}"><i class="fa fa-lock"></i> {% trans "Change password" %}</a>
                        </li>
                        <li class="{% ifequal request.path|slice:"-7:" "/email/" %}active{% endifequal %}">
                            <a href="{% url 'userena_email_change' user.username %}"><i class="fa fa-envelope-o"></i> {% trans "Change email" %}</a>
                        </li>
                    </ul>
                    <!-- END NAV TABS -->
                    <div class="tab-content profile-page">
                        {% if form.errors %}
                        <div class="alert alert-danger">
                            {% for field in form %}
                            {{ field.errors }}
                            {% endfor %}
                        </div> 
                        {% endif %}
                        <div>
                            <!-- <form role="form" class="form-horizontal"> -->
                                <fieldset>
                                    <form action="" enctype="multipart/form-data" method="post" class="form-horizontal">{% csrf_token %}

                                        {% for field in form %}
                                        
                                            <div class="form-group">
                                                <label class="col-lg-3 control-label data-row" for="recipient"><span class="data-name">{{field.label_tag}} {% if field.field.required %} * {% endif %} </span></label>
                                                <div class="col-lg-7">
                                                    
                                                    {% render_field field class+="form-control datePicker" %}
                                                    
                                                </div>
                                            </div>
                                          
                                        {% endfor %}
                                        </fieldset>
                                        <input class="btn btn-custom-primary" type="submit" value="{% trans "Save changes" %}"/>
                                    </form>
                                </fieldset>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

bazinga/templates/userena/signin_form.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}

{% block title %}{% trans "Signin" %}{% endblock %}

{% block content %}


<div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Please Sign In</h3>
                    </div>
                    <div class="panel-body">
                        <form role="form" action="" method="post">{% csrf_token %}
                            <fieldset>
                                <div class="form-group">
                                    <input class="form-control" placeholder="E-mail or username" name="identification" autofocus required>
                                </div>
                                <div class="form-group">
                                    <input class="form-control" placeholder="Password" name="password" type="password" value="" required>
                                </div>
                                <div class="checkbox">
                                    <label>
                                        <input name="remember_me" type="checkbox" value="Remember Me">Remember Me
                                    </label>
                                </div>
                                <!-- Change this to a button or input when using this as a form -->
                                <!-- <a href="index.html" class="btn btn-lg btn-success btn-block">Login</a> -->
                                <input type="submit" class="btn btn-success " value="{% trans "Signin" %}" />
                                <button type="button" class="btn">Cancel</button>
                                <p class="forgot-password"><a href="{% url 'userena_password_reset' %}" title="{% trans 'Forgot your password?' %}">{% trans "Forgot your password?" %}</a></p>
                                <div class="span4">
    
    <p class="signup"><a href="{% url 'userena_signup' %}" title="{% trans 'New here just signup' %}">{% trans "New here just signup" %}</a></p>
  </div>
  {% if form.errors %}
  <div class="alert alert-danger">
    {{ form.non_field_errors }}
        {% for field in form %}
        {{ field.errors }}
        {% endfor %}
  </div> 
  {% endif %}
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>



{% endblock %}

bazinga/templates/userena/signup_form.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}

{% block title %}{% trans "Signup" %}{% endblock %}
{% load staticfiles %}
{% load widget_tweaks %}
{% block content %}
{% include "navbar.html" %}
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <div class="main-header page-header">
                <h2>{% trans "Signup" %}</h2>
            </div>
        </div>         
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel-body">
                <div class="main-content">
                    <div class="row">
                        <div class="col-md-6 col-md-offset-3">
                            <div class="login-panel panel panel-default" style="margin-top: 0px;">
                                <div class="panel-heading">
                                    <h3 class="panel-title">All fields are required</h3>
                                </div>
                                <div class="panel-body">
                                    <form action="" method="post">
                                        {% csrf_token %}
                                        <fieldset>
                                            {% for field in form %}
                                            {{ field.errors }}
                                            {% comment %} Displaying checkboxes differently {% endcomment %}
                                            {% if field.name == 'tos' %}
                                            <p class="checkbox">
                                                <label for="id_{{ field.name }}">{{ field }} {{ field.label }}</label>
                                            </p>
                                            {% else %}
                                            <div class="form-group">
                                                <label class="col-lg-4 control-label data-row" for="recipient"><span class="data-name">{{field.label_tag}}</span></label>
                                                <div class="col-lg-7">
                                                    {% render_field field class+="form-control" %}
                                                    
                                                </div>
                                            </div>

                                            {% endif %}
                                            {% endfor %}
                                        </fieldset>
                                        <br/>
                                        <div class="col-md-12">
                                            <div class="col-md-6">
                                        <input class="btn btn-primary btn-block" type="submit" value="{% trans "Signup"%}" />
                                    </div>
                                        <div class="col-md-6">
                                        <input class="btn btn-default btn-block" type='button' value='Cancel' onclick="location.href='{% url 'home' %}'">
                                    </div>
                                    </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}